services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: markuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb

    # Pre-seed script is required as a volume to load mock database
    # Data inside the container is lost on restart unless you persist it with a volume.
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: marksdb
      DB_USER: markuser
      DB_PASSWORD: markspass
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000
    depends_on:
      - backend
    ports:
      - "8080:80"

  automark:
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug

volumes:
  db_data: